### ISSUE TITLE
[Feat]:  "Lock New Issues" GitHub Action to Reduce Notifications and Support

### ISSUE THREAD

**Issue by Nishitbaria** [JasonDsouza212/free-hit#1207]
### What feature?

As a repository maintainer, I propose the implementation of a workflow that aims to minimize notifications and enhance the support provided to maintainers. This workflow will automatically lock newly opened issues and provide guidance to contributors.

### Add screenshots

```
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          exclude-issue-labels: 'gssoc23.'
          process-only: 'issues'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label `gssoc23`. If you're participating in GSSoC'23, please add the `gssoc23` label to your issue.

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
