### ISSUE TITLE
[style]: Switching to scss for better readability and efficiency

### ISSUE THREAD

**Issue by USERSATOSHI** [JasonDsouza212/free-hit#416]
### What's the style idea?

I would like to switch the project stylesheet from css to scss

## Benefits

* Scss offers css nesting which allows use to skip repeating classnames when nesting css 
### Example

```css
.a  {
width:100%;
}

.a .b {
width:100%;
}

.a .b .c {
width:100%;
}
```

to 

```scss

.a {
	width: 100%;
	.b {
		width: 100%;
		.c {
			width: 100%;
		}
	}
}
```

*  mixins 
### example: 
```scss
  @mixin flexCenter { display: flex; justify-content: center; align-items: center; }
  .container { @include flexCenter; }
  ```
* inheritance
### example:
```scss
  .btn { padding: 10px; border: none; }
  .btn-primary { @extend .btn; background: blue; }
```
* functions
### example:
  ```scss
@function pxToRem($px) { @return $px / 16 * 1rem; }
  .container { font-size: pxToRem(16); }
```
* operators
### example:
```scss
  .container { width: 100% - 20px; }
  ```

these would make development easier and faster.
Vite supports scss natively
and you can use native css in scss as well

## Cons
Introducing scss to tech stack 

If this is possible I would like to work on this under GSSOC23

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
